#!/bin/bash

echo "=== GPU Node Access Methods on SLURM HPC Clusters ==="

echo -e "\n=== Method 1: Interactive SLURM Session ==="
echo "Use salloc to request an interactive allocation:"
echo "  salloc --partition=project4- --nodes=1 --ntasks-per-node=1 --gres=gpu:1 --time=01:00:00"
echo "After allocation is granted, you can ssh to the node or use srun to execute commands"

echo -e "\n=== Method 2: Interactive SLURM Shell ==="
echo "Use srun with --pty to get a shell directly on a compute node:"
echo "  srun --partition=project4- --nodes=1 --ntasks-per-node=1 --gres=gpu:1 --time=01:00:00 --pty bash -i"

echo -e "\n=== Method 3: Submit a Job with Shell Access ==="
echo "Create a batch script that keeps a shell open:"
echo "Example batch script (save as interactive_job.sh):"
echo "----------------------------------------"
echo "#!/bin/bash"
echo "#SBATCH --partition=project4-"
echo "#SBATCH --nodes=1"
echo "#SBATCH --ntasks-per-node=1"
echo "#SBATCH --gres=gpu:1"
echo "#SBATCH --time=01:00:00"
echo "#SBATCH --job-name=interactive"
echo ""
echo "# Print the node name so you know where to connect"
echo "echo \"Job running on node: \$(hostname)\""
echo ""
echo "# Keep the job running"
echo "sleep infinity"
echo "----------------------------------------"
echo "Submit with: sbatch interactive_job.sh"
echo "Then check the node with: squeue -u \$USER"
echo "Connect with: ssh \$(squeue -h -u \$USER -o %N -n interactive | head -1)"

echo -e "\n=== Method 4: Check Running Jobs and Connect ==="
echo "If you have running jobs, you can see them with:"
echo "  squeue -u \$USER"
echo "Then connect to the node where your job is running:"
echo "  ssh \$(squeue -h -u \$USER -o %N -j JOB_ID)"

echo -e "\n=== Method 5: Use srun to Execute Commands on Your Job's Node ==="
echo "If you already have a job running, you can execute commands on that node:"
echo "  srun --jobid=JOB_ID --pty bash -i"

echo -e "\n=== Note on Access Denied Errors ==="
echo "The 'Access denied by pam_slurm_adopt: you have no active jobs on this node' error occurs"
echo "when trying to SSH to a node where you don't have an active job allocation."
echo "Always use one of the methods above to ensure proper access." 